version: "3.3"
services:
    apache:
        container_name: apache
        build:
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - "8020:80"
        volumes:
            - ./:/var/www/html/
            - ./docker/config/apache:/etc/apache2/sites-enabled
            - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/config/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/config/xdebug/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        links:
            - mysql
    mysql:
        container_name: mysql
        image: mysql:8.0
        ports:
            - "33060:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: user
            MYSQL_PASSWORD: qwe
            MYSQL_ROOT_PASSWORD: qwe
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
            - "8000:80"
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: qwe
            MYSQL_ROOT_PASSWORD: qwe
